#- platform: yr
- platform: mqtt
  name: "Nuoc Nong Voltage"
  state_topic: "tele/sonoffpow1/SENSOR"
  value_template: "{{ value_json['ENERGY'].Voltage }}"
  unit_of_measurement: "V"
  availability_topic: "tele/sonoffpow1/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Nuoc Nong Current"
  state_topic: "tele/sonoffpow1/SENSOR"
  value_template: "{{ value_json['ENERGY'].Current | round(2) }}"
  unit_of_measurement: "A"
  availability_topic: "tele/sonoffpow1/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Nuoc Nong Power"
  state_topic: "tele/sonoffpow1/SENSOR"
  value_template: "{{ value_json['ENERGY'].Power }}"
  unit_of_measurement: "W"
  availability_topic: "tele/sonoffpow1/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Nuoc Nong Power Factor"
  state_topic: "tele/sonoffpow1/SENSOR"
  value_template: "{{ value_json['ENERGY'].Factor }}"
  availability_topic: "tele/sonoffpow1/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Nuoc Nong Energy Today"
  state_topic: "tele/sonoffpow1/SENSOR"
  value_template: "{{ value_json['ENERGY'].Today }}"
  unit_of_measurement: "kWh"
  availability_topic: "tele/sonoffpow1/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Nuoc Nong Energy Yesterday"
  state_topic: "tele/sonoffpow1/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday }}"
  unit_of_measurement: "kWh"
  availability_topic: "tele/sonoffpow1/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Nuoc Nong Energy Total"
  state_topic: "tele/sonoffpow1/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total }}"
  unit_of_measurement: "kWh"
  availability_topic: "tele/sonoffpow1/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

